[package]
name = "scheduler"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = { version = "*" }
csv = { version = "*" }
clap = { version = "*", features = ["derive"] }

[lib]
name = "sheduler"
parh = "src/lib.rs"

[[bin]]
name = "sheduler-cli"
path = "src/main.rs"
