[package]
name = "scheduler"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = { version = "*" }
csv = { version = "*" }
indexmap = { version = "*" }

[lib]
name = "scheduler"
parh = "src/lib.rs"
